from sqlalchemy import Column, Integer, String, Boolean, DateTime, Text, LargeBinary
from datetime import datetime

from app.db.database import Base


class User(Base):
    __tablename__ = "users"

    id = Column(Integer, primary_key=True, index=True)
    username = Column(String, unique=True, index=True, nullable=False)

    role_level = Column(Integer, nullable=False)
    clearance_level = Column(Integer, nullable=False)
    department = Column(String, nullable=False)

    is_active = Column(Boolean, default=True)

    created_at = Column(DateTime, default=datetime.utcnow)


class ConversationMessage(Base):
    """
    Stores multi-turn conversation messages.

    Each conversation is identified by a session_id (UUID generated by the client).
    Last 6 messages (3 turns) are fetched and included in the LLM prompt.
    """
    __tablename__ = "conversation_messages"

    id = Column(Integer, primary_key=True, index=True)
    session_id = Column(String, index=True, nullable=False)
    role = Column(String, nullable=False)  # "user" or "assistant"
    content = Column(Text, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow)


class Department(Base):
    __tablename__ = "departments"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String, unique=True, index=True, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow)


class Document(Base):
    __tablename__ = "documents"

    id = Column(Integer, primary_key=True, index=True)
    filename = Column(String, unique=True, index=True, nullable=False)
    owner_department = Column(String, nullable=False, default="shared")
    min_role_level = Column(Integer, nullable=False, default=1)
    min_clearance_level = Column(Integer, nullable=False, default=1)
    status = Column(String, nullable=False, default="uploaded")  # "uploaded", "ingesting", "ingested", "failed"
    file_content = Column(LargeBinary, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)


